#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : Introduccion a las Redes tensoriales  # The title of the book. Will be placed in the left navbar.
author                      : Comunidad sin nombre  # The author of the book
copyright                   : "2021"  # Copyright year to be placed in the footer
logo                        : logo.jpg  # A path to the book logo


repository:
  url                       : https://github.com/mcditoos/TensorNetworkBook.github.io
  path_to_book              : /Redes Tensoriales/
  branch                    : main

html:
  home_page_in_navbar         : false
  use_edit_page_button        : true
  use_repository_button       : true
  use_issue_button            : true

  
latex:
  latex_documents:
    targetname: book.tex
  latex_engine: pdflatex 


bibtex_bibfiles:
    - zreferences.bib

